# Generated by Django 5.0 on 2023-12-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.team'),
        ),
    ]
