# Generated by Django 5.0 on 2023-12-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_documento_em_transito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='em_transito',
        ),
    ]
